#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update && sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
redirect_me="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/listen 80 default_server;/a $redirect_me" /etc/nginx/sites-available/default
sudo service nginx restart
