#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
./1-install_nginx_web_server
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
