#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'
./1-install_nginx_web_server

# Create a 404 page
sudo mkdir -p /var/www/html/404
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404/index.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/listen 80 default_server;/a error_page 404 /404/index.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
