#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'
./1-install_nginx_web_server
sudo sed -i '/listen 80 default_server;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a location = /404.html {' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a root /var/www/html;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a internal;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a }' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx restart