#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
sudo apt update
sudo apt-get install -y haproxy
# Let HAProxy be able to be managed using init script
sudo  echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
sudo echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 55518-web-01 54.237.51.137:80 check\n\tserver 55518-web-02 54.85.131.160:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
