#!/usr/bin/env bash
# displays information about file
file="./bestschool"
if [ -e $file ]
then 
	echo "bestschool file exists"
	if [ -s $file ]
	then
		echo "bestschool file is not empty"
	else
		echo "bestschool file is empty"
	fi
	if [ -f $file ]
	then
		echo "bestschool is a regular file"
	fi
else
	echo "bestschool file does not exist"
fi
